name: smartcitizen-data
channels:
  - conda-forge
  - defaults
dependencies:
  - colorama
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets=7.5.*
  - joblib
  - json5
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_contrib_core
  - jupyter_core
  - jupyterlab
  - keras
  - markdown
  - markupsafe
  - matplotlib
  - numpy
  - pandas=0.23.*
  - pickleshare
  - pip=19.1.1
  - plotly=4.0.*
  - python=3.7
  - python-dateutil
  - pyyaml
  - requests
  - ruamel_yaml
  - scikit-learn=0.21.*
  - scipy
  - seaborn
  - shapely
  - statsmodels
  - tensorflow=1.13.*
  - urllib3
  - werkzeug
  - widgetsnbextension
  - xgboost
  - xlsxwriter
  - yaml
  - pip:
    - tabulate
    - pdfrw
    - reportlab
    - termcolor
    - tzwhere