# This is a configuration file for the Sensor Analysis Framework

data:
  combined_devices_name: 'COMBINED_DEVICES'
  reload_firmware_names: true
test:
  # In hours, cached data margin for reload
  cached_data_margin: 1  
  load_cached_API: true
  store_cached_API: true
  clean_na: null
models:
  # THIS WILL BE APPENDED TO YOUR MODEL IF YOU USE MULTIPLE TRAINING DATASETS
  name_multiple_training_data: 'CDEV'

# NOTES:
# Create a document called secrets.py and put your zenodo Personal access token there, following this:
# zenodo_token='your_token_here'